### ISSUE TITLE
Use appropriate resource mapping in handler methods

### ISSUE THREAD

**Issue by imneetkaur** [vka007/Spring-Boot-Task#11]
@GetMapping("track")  - use tracks
 @PutMapping(value = "/update/{id}/{comment}") - use /track/{id}/{comment}
@DeleteMapping(value = "/delete/{id}") - use /track/{id}

**Comment by vka007** [comment]
Resource Mapping Changed and fixed. Appropriate mapping used as specified in all the branches.
